### ISSUE TITLE
Make AlgoKit work with Universal apps

### ISSUE THREAD

**Issue by sirxyzzy** [pgolebiowski/algo-kit#1]
If I use nuget to grab AlgoKit to use in a Universal windows Application I get an error

Package AlgoKit 0.0.19 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package AlgoKit 0.0.19 supports: net (.NETFramework,Version=v0.0)

I plan to directly grab source, build myself, as in other regards I like the look of the code quality, compared to many efforts out there.

My application is pathfinding in a non-commercial game

**Comment by sirxyzzy** [comment]
Do I get a prize for issue number one :-)

**Comment by sirxyzzy** [comment]
I was pretty easily able to convert AlgoKit to a portable library using VS 2015, if you are interested I can send you a copy to look at... I have it set so it is compatible with .NET Framework, Core and Universal

**Comment by sirxyzzy** [comment]
No source changes, just extreme project file reorganization, I created a new Portable library, added all the code, compiled, presto!

**Comment by pgolebiowski** [comment]
Hi @andyphilpotts! I am extremely happy you like the quality of the code! I've just been looking at converting projects to .NET Core, but since you have already converted it, I would be more than happy to see what you came up with! 😄 It would be great if you could send me the project (ortorektyk@gmail.com) or make a pull request.

**Comment by sirxyzzy** [comment]
https://github.com/andyphilpotts/algo-kit

Forked your stuff, as a first pass this is JUST the code, not the tests etc...

**Comment by sirxyzzy** [comment]
The nice thing with portable is that one codebase should be able to deal with all curent platforms, that you use nice simple C# makes this very easy.

My path-finder based on Dijkstra's algorithm using your heap worked first time

**Comment by pgolebiowski** [comment]
@andyphilpotts, I've modified the project quite significantly. I migrated it to .NET Core actually, now it builds on App Veyor and tests run as expected. In theory it should now be easy to target any recent framework. Would it be possible for you to add the target you need?

> My path-finder based on Dijkstra's algorithm using your heap worked first time

:-)

**Comment by sirxyzzy** [comment]
I got nowhere with that, how do I add a target? I am not in .NET.Core here, this is Universal app land...

If I try to add the project as a ref, it merely says that a DLL or EXE is required.

Sorry, no idea how to consume this in UWP

**Comment by pgolebiowski** [comment]
Unfortunately it seems that .NET Core is not as established as I hoped - in fact it was announced only 2.5 months ago. There are missing features in ReShaper and the documentation is scarce. What is more important though is that in Q4 2016 / Q1 2017 they will be

> focused on replacing .xproj/project.json with .csproj/MSBuild

That would mean another reorganization and issues with configuration. I've decided to leave the library in its current shape until that time.

**Comment by sirxyzzy** [comment]
Makes sense to me, are you OK if I use your source code embedded, at least until and if you can get UWP support in place?

My thing is just a toy project, not commercial or anything.

**Comment by pgolebiowski** [comment]
Sure, it's ok :) But in order to use the library you must star it! 😄 I'll update this issue when the library gets support for UWP.

**Comment by pgolebiowski** [comment]
Targetting `netstandard2.0` now.
