### ISSUE TITLE
Can PairingHeap be made to preserve order of inserted elements?

### ISSUE THREAD

**Issue by kikaragyozov** [pgolebiowski/algo-kit#3]
If we want to use `PairingHeap<,>` as a priority queue implementation that allows having duplicate `TKey` values, is it possible to preserve their order of insertion? (FIFO)

I've switched to using `QuaternaryHeap` for now.

Thank you! 😄 

**EDIT:** Seems `QuaternaryHeap` has the same issue. Any ideas?

I'm aware that `.NET 6` has a `PriorityQueue` implementation, but it's very bare-bone. I can't remove an element, which is crucial for what I'm trying to do.

**Comment by pgolebiowski** [comment]
I don't remember which data structure was stable and which one wasn't, as I haven't looked into `PairingHeap` in a few years now. I thought array-based implementations of heaps are stable though...

Anyway, I can offer a general thought, maybe it'll help resolve your issue.

If you have a data structure that is prioritizes based on `TKey`, then you can simulate stability if your `TKey` is a tuple, with one value being whatever you want to store and the other value some sort of a timestamp / incremented id and have the `IComparer` compare first based on the value you want to store and then that timestamp.

**Comment by pgolebiowski** [comment]
I don't remember which data structure was stable and which one wasn't, as I haven't looked into `PairingHeap` in a few years now. I thought array-based implementations of heaps are stable though...

Anyway, I can offer a general thought, maybe it'll help resolve your issue.

If you have a data structure that is prioritized based on `TKey`, then you can simulate stability if your `TKey` is a tuple, with one value being whatever you want to store `TSomeThing` and the other value some sort of a timestamp / incremented id `TTimestamp` and have the `IComparer` compare first based on `TSomeThing` and then based on `TTimestamp`.

**Comment by kikaragyozov** [comment]
> I don't remember which data structure was stable and which one wasn't, as I haven't looked into `PairingHeap` in a few years now. I thought array-based implementations of heaps are stable though...
> 
> Anyway, I can offer a general thought, maybe it'll help resolve your issue.
> 
> If you have a data structure that is prioritized based on `TKey`, then you can simulate stability if your `TKey` is a tuple, with one value being whatever you want to store `TSomeThing` and the other value some sort of a timestamp / incremented id `TTimestamp` and have the `IComparer` compare first based on `TSomeThing` and then based on `TTimestamp`.

Yeah that was the approach I ended up using, thanks!
